# fly.toml app configuration file generated for stille-sewh8dpp1sfhhbxelxygac on 2024-10-18T16:10:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'michalkolacz-sewh8dpp1sfhhbxelxygac'
primary_region = 'waw'
kill_signal = "SIGINT"
kill_timeout = 5

[[vm]]
size = 'shared-cpu-1x'
memory = "512"

[experimental]
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
script_checks = []
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
hard_limit = 100
soft_limit = 80
type = "requests"

[http_service.concurrency]
type = "requests"
soft_limit = 80
hard_limit = 100

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

# [[services.tcp_checks]]
# grace_period = "1s"
# interval = "15s"
# restart_limit = 0
# timeout = "2s"

# [[services.http_checks]]
# interval = "10s"
# grace_period = "5s"
# method = "GET"
# path = "/resources/healthcheck"
# protocol = "http"
# timeout = "2s"
# tls_skip_verify = false
# headers = {}
