name: 👷 Pull request workflow
on:
  pull_request: { branches: "*" }
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  pull_request:
    name: 🕵️ Pull request
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: 📥 Download deps
        uses: bahmutov/npm-install@6cee6086f1bf4467050e9a51e94bfb71b44cbc39

      - name: 🏗️ Build project
        run: npm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 📘 Check types
        run: npm run typecheck

      - name: 📐 Lint code
        run: npm run lint

      - name: 💅 Prettier format
        run: npm run format:check
