name: Stage deployment
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  deploy:
    name: Deploy app to staging environment
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: github.event.head_commit.author.name != 'dependabot[bot]'
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: "fly.toml"
          field: "app"

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Deploy Staging
        run:
          flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --build-secret SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN}}
          --build-secret SENTRY_ORG=${{ secrets.SENTRY_ORG }} --build-secret SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
          --app ${{ steps.app_name.outputs.value }}-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
